spring.application.name=demo


spring.datasource.url=jdbc:mysql://localhost:3307/shop

spring.datasource.username=root
spring.datasource.password=valkova_thesis!1982Robin

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect

